package main

import "google.golang.org/protobuf/compiler/protogen"

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + ".gin.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-gin. DO NOT EDIT.")
	g.P("// versions:")
	g.P()
	return g
}
